language: php
sudo: false
php:
  - 7.3
  - 7.2
  - 7.1
install:
  - composer install --optimize-autoloader --prefer-dist --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter
